# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    v1.docs.serverless.com
#
# Happy Coding!

service: reversi # NOTE: update this with your service name

provider:
    name: aws
    runtime: nodejs4.3
    apiKeys:
        - reversi-${opt:stage}
    timeout: 300
    stage: dev
    region: us-east-1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
    loggedIn:
        handler: logged_in.handler
        events:
            - http:
                path: logged_in
                method: get
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - X-Reversi-Auth

    login:
        handler: login.handler
        events:
            - http:
                path: login
                method: post
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token

    game:
        handler: game.handler
        events:
            - http:
                path: game
                method: get
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - X-Reversi-Auth

    refreshLogin:
        handler: refresh_login.handler
        events:
            - http:
                path: refresh_login
                method: put
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - X-Reversi-Auth

    logout:
        handler: logout.handler
        events:
            - http:
                path: logout
                method: put
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - X-Reversi-Auth

    sendInvite:
        handler: invite.send_invite
        events:
            - http:
                path: invite
                method: post
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - X-Reversi-Auth

    acceptInvite:
        handler: invite.accept_invite
        events:
            - http:
                path: invite
                method: put
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - X-Reversi-Auth

    cancelInvite:
        handler: invite.cancel_invite
        events:
            - http:
                path: invite
                method: delete
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - X-Reversi-Auth


    getUser:
        handler: user.get
        events:
            - http:
                path: user
                method: get
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - X-Reversi-Auth

    deleteUser:
        handler: user.delete
        events:
            - http:
                path: user
                method: delete
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - X-Reversi-Auth

    getFriend:
        handler: friend.get
        events:
            - http:
                path: friend
                method: get
                private: true
                cors:
                    origins:
                        - '*'
                    headers:
                        - Content-Type
                        - X-Amz-Date
                        - Authorization
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - X-Reversi-Auth
#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
